import type { KnownOpenAIModelId, ModelClass, ModelLifecycle, ModelMetadata } from '../types.js';

function createOpenAIModel(
  rid: string,
  displayName: string,
  modelClass: ModelClass,
  isReasoning: boolean,
  lifecycle: ModelLifecycle,
  supportsVision = modelClass !== 'codex',
): ModelMetadata {
  return {
    rid,
    provider: 'openai',
    displayName,
    modelClass,
    isReasoning,
    supportsVision,
    supportsResponses: true,
    lifecycle,
  };
}

export const OPENAI_MODELS = {
  'gpt-4.1': createOpenAIModel(
    'ri.language-model-service..language-model.gpt-4-1',
    'GPT-4.1',
    'heavyweight',
    false,
    'ga',
  ),
  'gpt-4.1-mini': createOpenAIModel(
    'ri.language-model-service..language-model.gpt-4-1-mini',
    'GPT-4.1 Mini',
    'lightweight',
    false,
    'ga',
  ),
  'gpt-4.1-nano': createOpenAIModel(
    'ri.language-model-service..language-model.gpt-4-1-nano',
    'GPT-4.1 Nano',
    'lightweight',
    false,
    'ga',
  ),
  'gpt-4o': createOpenAIModel(
    'ri.language-model-service..language-model.gpt-4-o',
    'GPT-4o',
    'heavyweight',
    false,
    'ga',
  ),
  'gpt-4o-mini': createOpenAIModel(
    'ri.language-model-service..language-model.gpt-4-o-mini',
    'GPT-4o Mini',
    'lightweight',
    false,
    'ga',
  ),
  'gpt-5': createOpenAIModel(
    'ri.language-model-service..language-model.gpt-5',
    'GPT-5',
    'heavyweight',
    true,
    'ga',
  ),
  'gpt-5-codex': createOpenAIModel(
    'ri.language-model-service..language-model.gpt-5-codex',
    'GPT-5 Codex',
    'codex',
    false,
    'ga',
    false,
  ),
  'gpt-5-mini': createOpenAIModel(
    'ri.language-model-service..language-model.gpt-5-mini',
    'GPT-5 Mini',
    'lightweight',
    true,
    'ga',
  ),
  'gpt-5-nano': createOpenAIModel(
    'ri.language-model-service..language-model.gpt-5-nano',
    'GPT-5 Nano',
    'lightweight',
    true,
    'ga',
  ),
  'gpt-5.1': createOpenAIModel(
    'ri.language-model-service..language-model.gpt-5-1',
    'GPT-5.1',
    'heavyweight',
    false,
    'ga',
  ),
  'gpt-5.1-codex': createOpenAIModel(
    'ri.language-model-service..language-model.gpt-5-1-codex',
    'GPT-5.1 Codex',
    'codex',
    false,
    'ga',
    false,
  ),
  'gpt-5.1-codex-mini': createOpenAIModel(
    'ri.language-model-service..language-model.gpt-5-1-codex-mini',
    'GPT-5.1 Codex Mini',
    'codex',
    false,
    'ga',
    false,
  ),
  'gpt-5.2': createOpenAIModel(
    'ri.language-model-service..language-model.gpt-5-2',
    'GPT-5.2',
    'heavyweight',
    true,
    'experimental',
  ),
  'gpt-5.4': createOpenAIModel(
    'ri.language-model-service..language-model.gpt-5-4',
    'GPT-5.4',
    'heavyweight',
    true,
    'experimental',
  ),
  o3: createOpenAIModel(
    'ri.language-model-service..language-model.o-3',
    'o3',
    'reasoning',
    true,
    'ga',
  ),
  'o4-mini': createOpenAIModel(
    'ri.language-model-service..language-model.o-4-mini',
    'o4 Mini',
    'reasoning',
    true,
    'ga',
  ),
} as const satisfies Record<KnownOpenAIModelId, ModelMetadata>;
